services:
  # Postgres 설정
  # - https://hub.docker.com/_/postgres
  db:
    image: postgres:14.5-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: my-app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  keycloak-db:
    image: postgres:10
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  # Keycloak 설정
  # - https://www.keycloak.org/getting-started/getting-started-docker
  keycloak:
    depends_on:
      - keycloak-db
    image: quay.io/keycloak/keycloak:19.0.3
    ports:
      - 8080:8080
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # DB 연결 정보 (https://www.keycloak.org/server/db)
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    volumes:
      - ./themes:/opt/keycloak/themes

  # cache-db:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   command: redis-server --save 20 1 --loglevel warning --requirepass admin

volumes:
  db-data:
  keycloak-db-data:
  # redis-data: "./data/redis-data"
